spring.application.name=EcommercePlatform
server.port=9111

spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:ecomDb
spring.datasource.username=user
spring.datasource.password=

spring.jpa.show-sql=true